import os
import secrets

# Used to indicate that a value is optional (can be None)
from typing import Optional

# FastAPI is used to create the web API.
# HTTPException is used to return proper error messages.
# Depends is used to run authentication before the endpoint.
from fastapi import Depends, FastAPI, HTTPException, status

# HTTPBearer reads the Authorization: Bearer <token> header.
# HTTPAuthorizationCredentials stores the token sent by the client.
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from dotenv import load_dotenv
from pydantic import BaseModel

from agent import process_message

# NEW
from sessions import (
    get_session_response_id,
    save_session_response_id,
)


# Load environment variables from the .env file.
load_dotenv()

# Read our API token from the environment.
API_TOKEN = os.getenv("API_TOKEN")

# Stop immediately if API_TOKEN is missing.
if not API_TOKEN:
    raise RuntimeError("API_TOKEN is missing from the .env file.")


# Creates the Bearer-token authentication scheme.
security = HTTPBearer()


# Create the FastAPI application.
app = FastAPI(
    title="AI Developer Support Agent API",
    description="API access to the AI Developer Support Agent.",
    version="1.0.0",
)


# This function checks whether the provided API token is valid.
def verify_api_token(
    credentials: HTTPAuthorizationCredentials = Depends(security),
) -> str:
    # FastAPI first runs `security` (HTTPBearer()) before entering this function.
    # HTTPBearer() reads the Authorization header from the request.
    # Example: Authorization: Bearer abc123xyz
    # It then creates a `credentials` object containing:
    #   credentials.scheme = "Bearer"
    #   credentials.credentials = "abc123xyz"



    # you get smth like this : Authorization: Bearer abc123xyz
    # credentials.credentials contains only the token,
    # without the word "Bearer".
    provided_token = credentials.credentials

    # Compare the received token with the token stored in .env.
    if not secrets.compare_digest(provided_token, API_TOKEN):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API token.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    return provided_token


# This defines what the client must send to the API.
class ChatRequest(BaseModel):

    # The user's message and session ID.
    message: str
    session_id: str


# This defines what our API will return to the client.
class ChatResponse(BaseModel):

    # Indicates whether GPT answered directly
    # or whether it used one or more tools.
    type: str

    # The final answer generated by GPT.
    answer: str

    # The tool or tools GPT used.
    tool: str | list[str] | None = None

    # Needed for multi-turn conversations.
    response_id: str

    # Session ID of this conversation.
    session_id: str


@app.get("/")
async def root():

    return {
        "message": "AI Developer Support Agent API is running."
    }


@app.post("/chat", response_model=ChatResponse)
async def chat(
    request: ChatRequest,

    # Before chat() runs, FastAPI calls verify_api_token().
    # If the token is invalid, the request stops with a 401 error.
    authenticated_token: str = Depends(verify_api_token),
):

    try:

        # Get the latest OpenAI response ID for this session.
        previous_response_id = get_session_response_id(
            request.session_id
        )

        result = await process_message(
            user_message=request.message,
            previous_response_id=previous_response_id,
        )

        # Save the newest response ID for future messages.
        save_session_response_id(
            session_id=request.session_id,
            response_id=result["response_id"],
        )

        return ChatResponse(
            type=result["type"],
            answer=result["answer"],
            tool=result.get("tool"),
            response_id=result["response_id"],
            session_id=request.session_id,
        )

    except HTTPException:
        # Do not convert existing FastAPI errors into HTTP 500 errors.
        raise

    except Exception as error:
        raise HTTPException(
            status_code=500,
            detail=str(error),
        ) from error