# Used to indicate that a value is optional (can be None)
from typing import Optional
# FastAPI is used to create the web API.
# HTTPException is used to return proper error messages if something goes wrong.
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from agent import process_message # Import the chatbot's main processing function
# This is the same function used by main.py.


# Create the FastAPI application.
# The title, description, and version appear in the automatic API documentation (/docs).
app = FastAPI(
    title="AI Developer Support Agent API",
    description="API access to the AI Developer Support Agent.",
    version="1.0.0",
)



# This defines what the client must send to the API.
class ChatRequest(BaseModel):

    # The user's message and prev response ID
    message: str
    previous_response_id: Optional[str] = None



# This defines what our API will return to the client.
class ChatResponse(BaseModel):

    # Indicates whether GPT answered directly
    # or whether it used one or more tools.
    type: str

    # The final answer generated by GPT.
    answer: str

    # The tool(s) GPT used.
    # Can be:
    #   "get_account"
    #   ["search_documentation", "create_support_ticket"]
    #   None (if no tool was used)
    tool: str | list[str] | None = None

    # Needed for multi-turn conversations
    response_id: str



# If someone visits:
# http://localhost:8000/
# this function will execute.
@app.get("/")
async def root():

    # Simply confirms that the API is running.
    return {
        "message": "AI Developer Support Agent API is running."
    }




# This is the main endpoint.
# Clients send POST requests to:
# POST /chat
# along with a JSON body containing the user's message.
@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):

    try:
        
        # Pass the user's message into our existing chatbot.
        # This is exactly the same process used by main.py.
        result = await process_message(

            # User's message from the JSON request.
            user_message=request.message,

            # Previous conversation ID (if any).
            previous_response_id=request.previous_response_id,
        )

        # Convert the dictionary returned by process_message()
        # into the ChatResponse format.
        return ChatResponse(

            # Indicates whether GPT used tools.
            type=result["type"],

            # Final answer generated by GPT.
            answer=result["answer"],

            # Tool(s) used by GPT.
            tool=result.get("tool"),

            # Save this so future requests can continue
            # the same conversation.
            response_id=result["response_id"],
        )

    # If anything goes wrong, return an HTTP 500 error
    # instead of crashing the server.
    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error),
        ) from error