"""
Validates the SQL generated by the LLM before it is executed.
"""

# SQL operations that should never be allowed.
FORBIDDEN_WORDS = [
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "ALTER",
    "CREATE",
    "TRUNCATE",
]


def validate_sql(sql: str) -> str:
    """Checks that the generated SQL is safe to execute."""

    # Remove any extra whitespace.
    cleaned_sql = sql.strip()

    # Only allow SELECT queries.
    if not cleaned_sql.upper().startswith("SELECT"):
        raise ValueError("Only SELECT queries are allowed")

    upper_sql = cleaned_sql.upper()

    # Reject any forbidden SQL operations.
    for word in FORBIDDEN_WORDS:
        if word in upper_sql:
            raise ValueError(f"Forbidden SQL operation detected: {word}")

    return cleaned_sql